const test=require('node:test'),assert=require('node:assert/strict');
const {initial,validate,apply,view,CATALOG}=require('../app/state.cjs');
const now=1800000000000;
function configured(){let s=initial(now);return apply(s,'settings',s.settings,now).state;}
test('onboarding sets exact schedules; untouched flower starts wilted',()=>{let s=initial(now);assert.equal(view(s,now).wilted,true);assert.equal(view(s,now).waterDue,false);s=apply(s,'settings',s.settings,now).state;assert.equal(s.nextWaterAt,now+30*60000);assert.equal(s.nextStandAt,now+50*60000);assert.equal(s.onboarded,true);});
test('watering acknowledges drink, restores flower, resets timer; double click cannot farm rewards',()=>{let s=configured();s=apply(s,'water',{},now).state;assert.equal(view(s,now).wilted,false);assert.equal(s.waterings,1);assert.equal(s.rewardProgress,1);assert.throws(()=>apply(s,'water',{},now+100),/正在喝水/);assert.equal(s.waterings,1);assert.equal(view(s,now+30*60000).wilted,true);});
test('every third watering spawns five collectible coins and collection is one-time',()=>{let s=configured();for(let i=0;i<3;i++)s=apply(s,'water',{},now+i*3000).state;assert.equal(s.pendingCoins,5);assert.equal(s.coins,0);assert.equal(s.rewardProgress,0);s=apply(s,'collect',{},now).state;assert.equal(s.coins,5);assert.equal(s.pendingCoins,0);assert.throws(()=>apply(s,'collect',{},now));});
test('shop cannot overspend or buy invalid items; owned items equip for free',()=>{let s=configured();assert.throws(()=>apply(s,'buy',{id:'pot-cloud'},now),/金币/);assert.throws(()=>apply(s,'buy',{id:'not-real'},now));s.coins=25;s=apply(s,'buy',{id:'pot-cloud'},now).state;assert.equal(s.coins,15);assert.equal(s.equipped.pot,'pot-cloud');s=apply(s,'buy',{id:'pot-clay'},now).state;s=apply(s,'buy',{id:'pot-cloud'},now).state;assert.equal(s.coins,15);assert.equal(s.owned.filter(x=>x==='pot-cloud').length,1);});
test('water and stand timers are independent, once per cycle, and survive reload/sleep',()=>{let s=configured();let r=apply(s,'tick',{},now+60*60000);assert.deepEqual(r.result.due,['water','stand']);s=validate(JSON.parse(JSON.stringify(r.state)));assert.deepEqual(apply(s,'tick',{},now+90*60000).result.due,[]);s=apply(s,'stand',{},now+90*60000).state;assert.equal(view(s,now+90*60000).standDue,false);assert.equal(view(s,now+90*60000).waterDue,true);s=apply(s,'water',{},now+90*60000).state;assert.equal(view(s,now+90*60000).waterDue,false);});
test('settings validate atomically; disabling a reminder suppresses notifications',()=>{let s=configured(),raw=JSON.stringify(s);assert.throws(()=>apply(s,'settings',{...s.settings,waterMinutes:0},now));assert.equal(JSON.stringify(s),raw);s=apply(s,'settings',{...s.settings,waterEnabled:false},now).state;assert.deepEqual(apply(s,'tick',{},now+60*60000).result.due,['stand']);});
test('persisted state validates catalog, equipment and balances',()=>{const s=configured();assert.doesNotThrow(()=>validate(s));assert.throws(()=>validate({...s,coins:-1}));assert.throws(()=>validate({...s,equipped:{...s.equipped,pot:'can-mint'}}));assert.equal(CATALOG.length,12);assert.equal(new Set(CATALOG.map(x=>x.id)).size,12);});

