'use strict';
const $=s=>document.querySelector(s);let state,page=new URLSearchParams(location.search).get('page')||'settings',category='pot',messageTimer,loaded=false;
function message(text){$('#message').textContent=text;$('#message').classList.add('show');clearTimeout(messageTimer);messageTimer=setTimeout(()=>$('#message').classList.remove('show'),3300);}
function settings(){$('#water-minutes').value=String(state.settings.waterMinutes);$('#water-enabled').checked=state.settings.waterEnabled;$('#notifications').checked=state.settings.notifications;}
function renderReport(){const prompts=state.waterPrompts||[],answered=prompts.filter(p=>p.clickedAt!==null),times=answered.map(p=>p.responseMs).filter(Number.isFinite),average=times.length?Math.round(times.reduce((a,b)=>a+b,0)/times.length/1000):null,rate=times.length?Math.round(times.filter(ms=>ms<=5*60000).length/times.length*100):null;$('#report-prompts').textContent=String(prompts.length);$('#report-answered').textContent=String(answered.length);$('#report-average').textContent=average===null?'—':average<60?`${average} 秒`:`${Math.round(average/60)} 分钟`;$('#report-rate').textContent=rate===null?'—':`${rate}%`;$('#report-interval').textContent=`${state.settings.waterMinutes} 分钟`;$('#report-waterings').textContent=String(state.waterings);$('#report-coins').textContent=String(state.coins);$('#report-note').textContent=!answered.length?'先完成几次提醒，报告会逐渐有参考价值。':rate>=80?'你的回应很及时，当前提醒间隔比较适合你。':rate>=50?'大多数提醒都能回应，可以继续观察这个间隔。':'回应偏慢，可以尝试把提醒间隔调长一些。';}
function render(next){state=next;if(!loaded){settings();loaded=true;}$('#settings-page').hidden=page==='shop'||page==='report';$('#shop-page').hidden=page!=='shop';$('#report-page').hidden=page!=='report';$('#settings-title').textContent='提醒设置';$('#settings-eyebrow').textContent='SPROUT SETTINGS';$('#save-settings').textContent=page==='welcome'?'开始使用':'保存设置';PixelArt.flower($('#welcome-plant').getContext('2d'),{...state.equipped,bend:0});if(page==='shop')renderShop();if(page==='report')renderReport();}
function renderShop(){const focused=document.activeElement?.dataset.item;$('#wallet').textContent=String(state.coins);$('#owned').textContent=String(state.owned.length);const container=$('#items');container.replaceChildren();for(const item of state.catalog.filter(i=>i.type===category)){
 const equipped=state.equipped[item.type]===item.id,owned=state.owned.includes(item.id),card=document.createElement('article');card.className=`item${equipped?' equipped':''}`;card.title=item.detail;
 const canvas=document.createElement('canvas');canvas.width=canvas.height=64;const ctx=canvas.getContext('2d');if(category==='can'){ctx.scale(2,2);PixelArt.can(ctx,item.id);}else if(category==='pot'){ctx.translate(0,-12);PixelArt.pot(ctx,item.id);}else PixelArt.flower(ctx,{pot:state.equipped.pot,flower:item.id,bend:0});
 const name=document.createElement('h2');name.textContent=item.name;const button=document.createElement('button');button.dataset.item=item.id;button.disabled=equipped||(!owned&&state.coins<item.price);button.textContent=equipped?'使用中':owned?'换上它':`◈ ${item.price} 金币`;button.setAttribute('aria-label',`${item.name}：${button.textContent}`);if(!owned&&state.coins<item.price)button.title=`还差 ${item.price-state.coins} 枚金币`;button.addEventListener('click',async()=>{button.disabled=true;try{const r=await sprout.act('buy',{id:item.id});if(r.ok){render(r.state);message(`已换上${r.item}。`);}else{message(r.error);renderShop();}}catch{message('暂时无法兑换，请重试');renderShop();}});card.append(canvas,name,button);container.append(card);
 }if(focused)[...container.querySelectorAll('button')].find(b=>b.dataset.item===focused&&!b.disabled)?.focus();}
$('#settings-form').addEventListener('submit',async e=>{e.preventDefault();const payload={waterMinutes:Number($('#water-minutes').value),waterEnabled:$('#water-enabled').checked,notifications:$('#notifications').checked};$('#save-settings').disabled=true;try{const r=await sprout.act('settings',payload);if(!r.ok)message(r.error);}catch{message('设置未保存，请重试');}finally{$('#save-settings').disabled=false;}});
document.getElementById('water-minutes').addEventListener('wheel',event=>{event.preventDefault();const input=event.currentTarget;const value=Math.max(5,Math.min(180,Number(input.value)+(event.deltaY<0?5:-5)));input.value=String(value);},{passive:false});
document.querySelectorAll('[data-type]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.type;document.querySelectorAll('[data-type]').forEach(t=>t.setAttribute('aria-selected',String(t===b)));renderShop();}));
$('#report-open').addEventListener('click',()=>sprout.panel('report'));$('#report-back').addEventListener('click',()=>sprout.panel('settings'));$('#close').addEventListener('click',()=>sprout.closePanel());document.addEventListener('keydown',e=>{if(e.key==='Escape')sprout.closePanel();});sprout.onPage(next=>{page=next;settings();render(state);});sprout.onState(render);sprout.get().then(render).catch(()=>message('无法载入，请重新启动小芽。'));

